# This Dockerfile embeds a pre-built binary for the given Linux architecture
# Binaries must be built using "./scripts/development/build-binaries.sh --docker-only"

FROM gcr.io/distroless/static-debian12:nonroot

# TARGETARCH can be "amd64" or "arm64"
ARG TARGETARCH

WORKDIR /app

# UID & GID from https://github.com/GoogleContainerTools/distroless/blob/80eb8fae559f4a99916da1f8c1445d56b2c637f2/common/variables.bzl#L18
COPY --chown=65532:65532 ./backend/.bin/pocket-id-linux-${TARGETARCH} /app/pocket-id

EXPOSE 1411
ENV APP_ENV=production

HEALTHCHECK --interval=90s --timeout=5s --start-period=10s --retries=3 CMD [ "/app/pocket-id", "healthcheck" ]

CMD ["/app/pocket-id"]
